force-app/main/default/objects/Member__c/Member__c.object-meta.xml
<CustomObject>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member__c/fields/Joined_On__c.field-meta.xml
<CustomField>
    <fullName>Joined_On__c</fullName>
    <inlineHelpText>Date when the member joined the library.</inlineHelpText>
    <label>Joined On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Member_Security_Test.cls
public with sharing class Member_Security_Test {
    public Member__c member{get;set;}
    public Member_Security_Test() {
        Id recId = ApexPages.currentPage().getParameters().get('Id');
        member = [SELECT name, email__c, joined_on__c FROM Member__C
                 where Id = :recId];
    }
    public void save(){
        try{
            MemberDAO.updateMember(member);
        }
        catch(DmlException ex){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.FATAL, ex.getMessage()));
        }

    }
}