force-app/main/default/objects/Member__c/Member__c.object-meta.xml
<CustomObject>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member__c/fields/Joined_On__c.field-meta.xml
<CustomField>
    <fullName>Joined_On__c</fullName>
    <inlineHelpText>Date when the member joined the library.</inlineHelpText>
    <label>Joined On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/MemberExtension.cls
// This class is an extension to a standard controller
public with sharing class MemberExtension {
    
    public Member__c member {get; set;}
    private ApexPages.StandardController stdController;

    public MemberExtension() {

    }
    // for this class to be an extension to a standard controller it must have a constructor like
    public MemberExtension(ApexPages.StandardController stdController){
        this.stdController = stdController;
        List<String> fieldNames = new List<String>();
        fieldNames.add('Name');
        fieldNames.add('Joined_on__C');
        fieldNames.add('email__c');
        fieldNames.add('active__c');
        stdController.addFields(fieldNames);

        // getRecord() returns a variable of sObject so we are casting it to Member object
        // sObject s ---> here s is a generic sObject
        // Member__c m ---> here is a specific sOjbect
        member = (Member__c) stdController.getRecord();
    }

    public Pagereference save(){
        try {
            //System.debug('save method of extension called');
            update member;
        } catch (DmlException ex) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.FATAL,ex.getMessage()));
            return Apexpages.currentPage();
        }
        return stdController.view();
    }

}